### ISSUE TITLE
is this production ready?

### ISSUE THREAD

**Issue by pablomaurer** [rogerdcarvalho/CordovaUniversalAppServer#1]
is this production ready?
no changes since 6 months, no issues no nothing =) although so many people are in need of such a plugin.

PS: maybe with renaming it to something with cordova and adding a bit more documentation, people would start using it..

**Comment by rogerdcarvalho** [comment]
It is production ready, and is already in market in my app. I built it for use in my own app, and thought it would be useful to share with the public. Didn't really market it to other developers to start using. Good note to change the name, this might give it some more exposure!
